import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pl' | 'en' | 'uk' | 'be';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    nav_recording: 'Nagrywanie',
    nav_rehearsals: 'Próby',
    nav_rent: 'Wynajem',
    nav_price: 'Cennik',
    nav_contact: 'Kontakt',
    hero_title: 'Profesjonalne Studio Nagraniowe',
    hero_subtitle: 'Najwyższa jakość nagrań w sercu miasta',
    stat_clients: 'klientów',
    stat_songs: 'wydanych utworów',
    stat_rehearsals: 'prób',
    stat_rating: 'Ocena klientów 5★',
    recording_title: 'Usługi Nagraniowe',
    recording_desc: 'Oferujemy kompleksowe usługi nagraniowe z wykorzystaniem najnowocześniejszego sprzętu i doświadczonego zespołu inżynierów dźwięku.',
    recording_vocal_title: 'Nagrywanie Wokalu',
    recording_vocal_desc: 'Profesjonalna kabina wokalna z mikrofonami najwyższej klasy',
    recording_instrument_title: 'Nagrywanie Instrumentów',
    recording_instrument_desc: 'Pełne studio z wydzielonymi pokojami nagraniowymi',
    recording_mixing_title: 'Mixing & Mastering',
    recording_mixing_desc: 'Usługi miksowania i masteringu na poziomie branżowym',
    recording_production_title: 'Produkcja Audio',
    recording_production_desc: 'Kompleksowa produkcja audio od koncepcji po finalny miks',
    rehearsals_title: 'Sale Prób',
    rehearsals_desc: 'Profesjonalne sale prób wyposażone w pełen backline i nagłośnienie. Idealne dla zespołów każdego gatunku.',
    rehearsals_backline_title: 'Pełen Backline',
    rehearsals_backline_desc: 'Wzmacniacze, perkusja i system nagłośnienia w zestawie',
    rehearsals_acoustic_title: 'Wyciszenie Akustyczne',
    rehearsals_acoustic_desc: 'Profesjonalnie wyciszone pomieszczenia dla optymalnego brzmienia',
    rehearsals_booking_title: 'Elastyczna Rezerwacja',
    rehearsals_booking_desc: 'Wynajem godzinowy, dzienny lub miesięczny',
    rehearsals_climate_title: 'Klimatyzacja',
    rehearsals_climate_desc: 'Idealna temperatura i wilgotność dla instrumentów',
    rent_title: 'Wynajem Sprzętu',
    rent_desc: 'Wynajmij profesjonalny sprzęt muzyczny i nagłośnieniowy na Twoje wydarzenie.',
    rent_pa_title: 'Systemy Nagłośnieniowe',
    rent_pa_desc: 'Profesjonalne systemy nagłośnienia',
    rent_mics_title: 'Mikrofony',
    rent_mics_desc: 'Najlepsze mikrofony do każdego zastosowania',
    rent_stage_title: 'Sprzęt Sceniczny',
    rent_stage_desc: 'Kable, statywy i akcesoria sceniczne',
    rent_recording_title: 'Sprzęt Nagraniowy',
    rent_recording_desc: 'Przenośny sprzęt nagraniowy do pracy w terenie',
    price_title: 'Cennik',
    price_subtitle: 'Przejrzyste ceny za profesjonalne usługi',
    price_recording_name: 'Nagrywanie',
    price_recording_feature1: 'Profesjonalny inżynier dźwięku',
    price_recording_feature2: 'Pełny dostęp do sprzętu',
    price_recording_feature3: 'Dostarczenie plików cyfrowych',
    price_recording_feature4: 'Jedna korekta w cenie',
    price_rehearsal_name: 'Próby',
    price_rehearsal_feature1: 'Pełen backline w zestawie',
    price_rehearsal_feature2: 'Pełny dostęp do sprzętu',
    price_rehearsal_feature3: 'System nagłośnienia',
    price_rehearsal_feature4: 'Klimatyzacja',
    price_rehearsal_feature5: 'Elastyczne terminy',
    price_rental_name: 'Wynajem Sprzętu',
    price_rental_feature1: 'Profesjonalny system nagłośnienia',
    price_rental_feature2: 'Najlepsze mikrofony',
    price_rental_feature3: 'Perkusja',
    price_rental_feature4: 'Zestawy gitarowe i basowe',
    price_rental_feature5: 'Syntezatory',
    price_rental_feature6: 'Wszystkie kable w zestawie',
    price_rental_feature7: 'Wsparcie techniczne',
    price_mixing_name: 'Mixing & Mastering',
    price_mixing_feature1: 'Profesjonalny mixing',
    price_mixing_feature2: 'Mastering w cenie',
    price_mixing_feature3: 'Nieograniczone korekty',
    price_mixing_feature4: 'Jakość na poziomie branżowym',
    price_from: 'od',
    price_optional: 'Do ustalenia',
    footer_tagline: 'Profesjonalne Studio Nagraniowe i Sale Prób',
    contact_title: 'Kontakt',
    contact_subtitle: 'Napisz do nas i zarezerwuj swój termin',
    contact_name: 'Imię',
    contact_email: 'Email',
    contact_message: 'Wiadomość',
    contact_send: 'Wyślij',
    contact_success_title: 'Wiadomość wysłana',
    contact_success_desc: 'Dziękujemy! Odpowiemy najszybciej jak to możliwe.',
    contact_error_title: 'Błąd wysyłania',
    contact_error_desc: 'Spróbuj ponownie lub napisz bezpośrednio na support@sanctum-sa.com',
    contact_address: 'Adres',
    contact_phone: 'Telefon',
    contact_button: 'Skontaktuj się z nami',
    studio_gear_title: 'Sprzęt Studia',
    studio_gear_button: 'Zobacz pełną listę sprzętu',
    studio_gear_watch: 'Zobacz',
    book_button: 'Zarezerwuj',
  },
  en: {
    nav_recording: 'Recording',
    nav_rehearsals: 'Rehearsals',
    nav_rent: 'Rent',
    nav_price: 'Price',
    nav_contact: 'Contact',
    hero_title: 'Professional Recording Studio',
    hero_subtitle: 'Highest quality recordings in the heart of the city',
    stat_clients: 'clients',
    stat_songs: 'released songs',
    stat_rehearsals: 'rehearsals',
    stat_rating: '5 star clients rating',
    recording_title: 'Recording Services',
    recording_desc: 'We offer comprehensive recording services using state-of-the-art equipment and an experienced team of sound engineers.',
    recording_vocal_title: 'Vocal Recording',
    recording_vocal_desc: 'Professional vocal booth with top-tier microphones',
    recording_instrument_title: 'Instrument Recording',
    recording_instrument_desc: 'Full band setup with isolated tracking rooms',
    recording_mixing_title: 'Mixing & Mastering',
    recording_mixing_desc: 'Industry-standard mixing and mastering services',
    recording_production_title: 'Audio Production',
    recording_production_desc: 'Complete audio production from concept to final mix',
    rehearsals_title: 'Rehearsal Rooms',
    rehearsals_desc: 'Professional rehearsal rooms equipped with full backline and sound system. Perfect for bands of any genre.',
    rehearsals_backline_title: 'Full Backline',
    rehearsals_backline_desc: 'Amplifiers, drums, and PA system included',
    rehearsals_acoustic_title: 'Acoustic Treatment',
    rehearsals_acoustic_desc: 'Professionally treated rooms for optimal sound',
    rehearsals_booking_title: 'Flexible Booking',
    rehearsals_booking_desc: 'Hourly, daily, or monthly rental options',
    rehearsals_climate_title: 'Climate Control',
    rehearsals_climate_desc: 'Perfect temperature and humidity for instruments',
    rent_title: 'Equipment Rental',
    rent_desc: 'Rent professional music and sound equipment for your event.',
    rent_pa_title: 'PA Systems',
    rent_pa_desc: 'Professional sound reinforcement systems',
    rent_mics_title: 'Microphones',
    rent_mics_desc: 'Premium microphones for any application',
    rent_stage_title: 'Stage Equipment',
    rent_stage_desc: 'Cables, stands, and stage accessories',
    rent_recording_title: 'Recording Gear',
    rent_recording_desc: 'Portable recording equipment for field work',
    price_title: 'Pricing',
    price_subtitle: 'Transparent pricing for professional services',
    price_recording_name: 'Recording',
    price_recording_feature1: 'Professional sound engineer',
    price_recording_feature2: 'Full equipment access',
    price_recording_feature3: 'Digital file delivery',
    price_recording_feature4: 'One revision included',
    price_rehearsal_name: 'Rehearsal',
    price_rehearsal_feature1: 'Full backline included',
    price_rehearsal_feature2: 'Full equipment access',
    price_rehearsal_feature3: 'PA system',
    price_rehearsal_feature4: 'Climate controlled',
    price_rehearsal_feature5: 'Flexible scheduling',
    price_rental_name: 'Equipment Rental',
    price_rental_feature1: 'Professional PA system',
    price_rental_feature2: 'Premium microphones',
    price_rental_feature3: 'Drums',
    price_rental_feature4: 'Guitar and Bass stacks',
    price_rental_feature5: 'Synths',
    price_rental_feature6: 'All cables included',
    price_rental_feature7: 'Technical support',
    price_mixing_name: 'Mixing & Mastering',
    price_mixing_feature1: 'Professional mixing',
    price_mixing_feature2: 'Mastering included',
    price_mixing_feature3: 'Unlimited revisions',
    price_mixing_feature4: 'Industry standard quality',
    price_from: 'from',
    price_optional: 'Optional',
    footer_tagline: 'Professional Recording Studio & Rehearsal Space',
    contact_title: 'Contact',
    contact_subtitle: 'Feel free to reach out and book your appointment',
    contact_name: 'Name',
    contact_email: 'Email',
    contact_message: 'Message',
    contact_send: 'Send',
    contact_success_title: 'Message sent',
    contact_success_desc: 'Thanks! We will get back to you as soon as possible.',
    contact_error_title: 'Sending failed',
    contact_error_desc: 'Please try again or email us directly at support@sanctum-sa.com',
    contact_address: 'Address',
    contact_phone: 'Phone',
    contact_button: 'Contact Us',
    studio_gear_title: 'Studio Gear',
    studio_gear_button: 'View full equipment list',
    studio_gear_watch: 'Watch',
    book_button: 'Book',
  },
  uk: {
    nav_recording: 'Запис',
    nav_rehearsals: 'Репетиції',
    nav_rent: 'Оренда',
    nav_price: 'Ціни',
    nav_contact: 'Контакт',
    hero_title: 'Професійна Студія Звукозапису',
    hero_subtitle: 'Найвища якість записів у центрі міста',
    stat_clients: 'клієнтів',
    stat_songs: 'випущених пісень',
    stat_rehearsals: 'репетицій',
    stat_rating: '5★ рейтинг клієнтів',
    recording_title: 'Послуги Звукозапису',
    recording_desc: 'Ми пропонуємо комплексні послуги звукозапису з використанням найсучаснішого обладнання та досвідченої команди звукоінженерів.',
    recording_vocal_title: 'Запис Вокалу',
    recording_vocal_desc: 'Професійна вокальна кабіна з мікрофонами вищого класу',
    recording_instrument_title: 'Запис Інструментів',
    recording_instrument_desc: 'Повна установка для гурту з ізольованими кімнатами',
    recording_mixing_title: 'Мікшування та Мастеринг',
    recording_mixing_desc: 'Професійні послуги мікшування та мастерингу',
    recording_production_title: 'Аудіо Продакшн',
    recording_production_desc: 'Повне аудіо виробництво від концепції до фінального міксу',
    rehearsals_title: 'Репетиційні Зали',
    rehearsals_desc: 'Професійні репетиційні зали, обладнані повним беклайном та звуковою системою. Ідеально підходять для гуртів будь-якого жанру.',
    rehearsals_backline_title: 'Повний Беклайн',
    rehearsals_backline_desc: 'Підсилювачі, барабани та звукова система в комплекті',
    rehearsals_acoustic_title: 'Акустична Обробка',
    rehearsals_acoustic_desc: 'Професійно оброблені приміщення для оптимального звуку',
    rehearsals_booking_title: 'Гнучке Бронювання',
    rehearsals_booking_desc: 'Погодинна, денна або місячна оренда',
    rehearsals_climate_title: 'Клімат-Контроль',
    rehearsals_climate_desc: 'Ідеальна температура та вологість для інструментів',
    rent_title: 'Оренда Обладнання',
    rent_desc: 'Орендуйте професійне музичне та звукове обладнання для вашої події.',
    rent_pa_title: 'Звукові Системи',
    rent_pa_desc: 'Професійні системи озвучування',
    rent_mics_title: 'Мікрофони',
    rent_mics_desc: 'Преміальні мікрофони для будь-яких застосувань',
    rent_stage_title: 'Сценічне Обладнання',
    rent_stage_desc: 'Кабелі, стійки та сценічні аксесуари',
    rent_recording_title: 'Обладнання для Запису',
    rent_recording_desc: 'Портативне обладнання для запису у полі',
    price_title: 'Ціни',
    price_subtitle: 'Прозоре ціноутворення на професійні послуги',
    price_recording_name: 'Запис',
    price_recording_feature1: 'Професійний звукоінженер',
    price_recording_feature2: 'Повний доступ до обладнання',
    price_recording_feature3: 'Доставка цифрових файлів',
    price_recording_feature4: 'Одна правка включена',
    price_rehearsal_name: 'Репетиція',
    price_rehearsal_feature1: 'Повний беклайн включено',
    price_rehearsal_feature2: 'Повний доступ до обладнання',
    price_rehearsal_feature3: 'Звукова система',
    price_rehearsal_feature4: 'Клімат-контроль',
    price_rehearsal_feature5: 'Гнучкий графік',
    price_rental_name: 'Оренда Обладнання',
    price_rental_feature1: 'Професійна звукова система',
    price_rental_feature2: 'Преміальні мікрофони',
    price_rental_feature3: 'Барабани',
    price_rental_feature4: 'Гітарні та басові стеки',
    price_rental_feature5: 'Синтезатори',
    price_rental_feature6: 'Усі кабелі включено',
    price_rental_feature7: 'Технічна підтримка',
    price_mixing_name: 'Мікшування та Мастеринг',
    price_mixing_feature1: 'Професійне мікшування',
    price_mixing_feature2: 'Мастеринг включено',
    price_mixing_feature3: 'Необмежені правки',
    price_mixing_feature4: 'Якість промислового стандарту',
    price_from: 'від',
    price_optional: 'Опціонально',
    footer_tagline: 'Професійна Студія Звукозапису та Репетиційні Зали',
    contact_title: 'Контакт',
    contact_subtitle: "Зв'яжіться з нами та забронюйте свій візит",
    contact_name: "Ім'я",
    contact_email: 'Email',
    contact_message: 'Повідомлення',
    contact_send: 'Надіслати',
    contact_success_title: 'Повідомлення надіслано',
    contact_success_desc: 'Дякуємо! Ми відповімо якнайшвидше.',
    contact_error_title: 'Помилка надсилання',
    contact_error_desc: 'Спробуйте ще раз або напишіть на support@sanctum-sa.com',
    contact_address: 'Адреса',
    contact_phone: 'Телефон',
    contact_button: 'Зв\'яжіться з нами',
    studio_gear_title: 'Обладнання Студії',
    studio_gear_button: 'Переглянути повний список обладнання',
    studio_gear_watch: 'Переглянути',
    book_button: 'Забронювати',
  },
  be: {
    nav_recording: 'Запіс',
    nav_rehearsals: 'Рэпетыцыі',
    nav_rent: 'Арэнда',
    nav_price: 'Кошты',
    nav_contact: 'Кантакт',
    hero_title: 'Прафесійная Студыя Гукозапісу',
    hero_subtitle: 'Найвышэйшая якасць запісаў у цэнтры горада',
    stat_clients: 'кліентаў',
    stat_songs: 'выпушчаных песень',
    stat_rehearsals: 'рэпетыцый',
    stat_rating: '5★ рэйтынг кліентаў',
    recording_title: 'Паслугі Гукозапісу',
    recording_desc: 'Мы прапануем комплексныя паслугі гукозапісу з выкарыстаннем найсучаснейшага абсталявання і вопытнай каманды гукарэжысёраў.',
    recording_vocal_title: 'Запіс Вакалу',
    recording_vocal_desc: 'Прафесійная вакальная кабіна з мікрафонамі вышэйшай класы',
    recording_instrument_title: 'Запіс Інструментаў',
    recording_instrument_desc: 'Поўная ўстаноўка для гурта з ізаляванымі пакоямі',
    recording_mixing_title: 'Мікшаванне і Мастэрынг',
    recording_mixing_desc: 'Прафесійныя паслугі мікшавання і мастэрынгу',
    recording_production_title: 'Аўдыё Прадакшн',
    recording_production_desc: 'Поўная аўдыё вытворчасць ад канцэпцыі да фінальнага міксу',
    rehearsals_title: 'Рэпетыцыйныя Залы',
    rehearsals_desc: 'Прафесійныя рэпетыцыйныя залы, абсталяваныя поўным беклайнам і гукавой сістэмай. Ідэальна падыходзяць для гуртоў любога жанру.',
    rehearsals_backline_title: 'Поўны Беклайн',
    rehearsals_backline_desc: 'Узмацняльнікі, барабаны і гукавая сістэма ў комплекце',
    rehearsals_acoustic_title: 'Акустычная Апрацоўка',
    rehearsals_acoustic_desc: 'Прафесійна апрацаваныя памяшканні для аптымальнага гуку',
    rehearsals_booking_title: 'Гібкае Браніраванне',
    rehearsals_booking_desc: 'Пагадзінная, дзённая або месячная арэнда',
    rehearsals_climate_title: 'Клімат-Кантроль',
    rehearsals_climate_desc: 'Ідэальная тэмпература і вільготнасць для інструментаў',
    rent_title: 'Арэнда Абсталявання',
    rent_desc: 'Арандуйце прафесійнае музычнае і гукавое абсталяванне для вашай падзеі.',
    rent_pa_title: 'Гукавыя Сістэмы',
    rent_pa_desc: 'Прафесійныя сістэмы азвучвання',
    rent_mics_title: 'Мікрафоны',
    rent_mics_desc: 'Прэміяльныя мікрафоны для любых прымяненняў',
    rent_stage_title: 'Сцэнічнае Абсталяванне',
    rent_stage_desc: 'Кабелі, стойкі і сцэнічныя аксесуары',
    rent_recording_title: 'Абсталяванне для Запісу',
    rent_recording_desc: 'Партатыўнае абсталяванне для запісу ў полі',
    price_title: 'Кошты',
    price_subtitle: 'Празрыстае цэнаўтварэнне на прафесійныя паслугі',
    price_recording_name: 'Запіс',
    price_recording_feature1: 'Прафесійны гукарэжысёр',
    price_recording_feature2: 'Поўны доступ да абсталявання',
    price_recording_feature3: 'Дастаўка лічбавых файлаў',
    price_recording_feature4: 'Адна праўка ўключана',
    price_rehearsal_name: 'Рэпетыцыя',
    price_rehearsal_feature1: 'Поўны беклайн уключаны',
    price_rehearsal_feature2: 'Поўны доступ да абсталявання',
    price_rehearsal_feature3: 'Гукавая сістэма',
    price_rehearsal_feature4: 'Клімат-кантроль',
    price_rehearsal_feature5: 'Гібкі графік',
    price_rental_name: 'Арэнда Абсталявання',
    price_rental_feature1: 'Прафесійная гукавая сістэма',
    price_rental_feature2: 'Прэміяльныя мікрафоны',
    price_rental_feature3: 'Барабаны',
    price_rental_feature4: 'Гітарныя і басавыя стэкі',
    price_rental_feature5: 'Сінтэзатары',
    price_rental_feature6: 'Усе кабелі ўключаны',
    price_rental_feature7: 'Тэхнічная падтрымка',
    price_mixing_name: 'Мікшаванне і Мастэрынг',
    price_mixing_feature1: 'Прафесійнае мікшаванне',
    price_mixing_feature2: 'Мастэрынг уключаны',
    price_mixing_feature3: 'Неабмежаваныя праўкі',
    price_mixing_feature4: 'Якасць прамысловага стандарту',
    price_from: 'ад',
    price_optional: 'Апцыянальна',
    footer_tagline: 'Прафесійная Студыя Гукозапісу і Рэпетыцыйныя Залы',
    contact_title: 'Кантакт',
    contact_subtitle: 'Звяжыцеся з намі і забраніруйце свой візіт',
    contact_name: 'Імя',
    contact_email: 'Email',
    contact_message: 'Паведамленне',
    contact_send: 'Адправіць',
    contact_success_title: 'Паведамленне адпраўлена',
    contact_success_desc: 'Дзякуем! Мы адкажам як мага хутчэй.',
    contact_error_title: 'Памылка адпраўкі',
    contact_error_desc: 'Паспрабуйце яшчэ раз або напішыце на support@sanctum-sa.com',
    contact_address: 'Адрас',
    contact_phone: 'Тэлефон',
    contact_button: 'Звяжыцеся з намі',
    studio_gear_title: 'Абсталяванне Студыі',
    studio_gear_button: 'Паглядзець поўны спіс абсталявання',
    studio_gear_watch: 'Паглядзець',
    book_button: 'Забраніраваць',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect browser language and set default
const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase();
  
  // Map browser language codes to our supported languages
  if (browserLang.startsWith('pl')) return 'pl';
  if (browserLang.startsWith('uk')) return 'uk';
  if (browserLang.startsWith('be')) return 'be';
  if (browserLang.startsWith('en')) return 'en';
  
  // Default to English if language not supported
  return 'en';
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check if language is stored in localStorage
    const storedLang = localStorage.getItem('language') as Language | null;
    if (storedLang && ['pl', 'en', 'uk', 'be'].includes(storedLang)) {
      return storedLang;
    }
    // Otherwise, detect browser language
    return detectBrowserLanguage();
  });

  // Save language preference to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
