import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pl' | 'en' | 'uk' | 'be';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    nav_recording: 'Nagrywanie',
    nav_rehearsals: 'Próby',
    nav_rent: 'Wynajem',
    nav_price: 'Cennik',
    nav_contact: 'Kontakt',
    hero_title: 'Profesjonalne Studio Nagraniowe',
    hero_subtitle: 'Najwyższa jakość nagrań w sercu miasta',
    stat_clients: 'klientów',
    stat_songs: 'wydanych utworów',
    stat_rehearsals: 'prób',
    stat_rating: 'Ocena klientów 5★',
    recording_title: 'Usługi Nagraniowe',
    recording_desc: 'Oferujemy kompleksowe usługi nagraniowe z wykorzystaniem najnowocześniejszego sprzętu i doświadczonego zespołu inżynierów dźwięku.',
    recording_vocal_title: 'Nagranie wokalu',
    recording_vocal_desc: 'Nagranie wokalu w studiu wyposażonym w nowoczesny sprzęt. Nagrywamy do utworów muzycznych, rapu, podcastów, reklam i td. U nas możesz oczekiwać na zyste brzmienie, komfortową atmosferę i indywidualne podejście, które pozwolą w pełni wykorzystać potencjał Twojego głosu',
    recording_instrument_title: 'Nagrania instrumentów',
    recording_instrument_desc: 'Profesjonalne nagrania instrumentów muzycznych w doskonale przygotowanych warunkach akustycznych. Rejestrujemy gitary, bas, perkusję, instrumenty klawiszowe, smyczkowe i dęte, dbając o najwyższą jakość dźwięku. Mamy sprzęt z wysokiej półki, mikrofony takich marek jak Audix, Shure, Behringer, AKG, Sennheiser gwarantują naturalne, szczegółowe brzmienie gotowe do miksu i masteringu',
    recording_mixing_title: 'Mix i mastering',
    recording_mixing_desc: 'Profesjonalny mix i mastering. Dbamy o odpowiedni balans, dynamikę oraz przestrzeń w nagraniu, aby Twoja muzyka brzmiała doskonale na wszystkich platformach i systemach odsłuchowych. Każdy projekt traktujemy indywidualnie, podkreślając jego charakter i potencjał. Oferujemy również edycję wokalu, prostowanie ścieżek perkusji i tp',
    recording_production_title: 'Produkcja Audio',
    recording_production_desc: 'Masz pomysł na piosenkę, ale nie wiesz, jak zamienić go w profesjonalny utwór? Oferujemy kompleksową realizację muzyczną od pierwszej koncepcji aż po gotowy materiał do publikacji. Pomagamy w opracowaniu aranżacji, realizujemy nagrania wokalu i instrumentów, a następnie zajmujemy się edycją, miksem i masteringiem',
    rehearsals_title: 'Sale Prób',
    rehearsals_desc: 'Profesjonalne sale prób wyposażone w pełen backline i nagłośnienie. Idealne dla zespołów każdego gatunku.',
    rehearsals_backline_title: 'Pełen Backline',
    rehearsals_backline_desc: 'Oferujemy wzmacniacze lampowe gitarowe i basowe, zestaw perkusyjny w pełni wyposażony do grania, oraz wysokiej jakości sprzęt nagłośnieniowy 800 Watt. Wszystko serwisowane na bieżąco, wyposażenie zapewnia niezawodność, komfort gry i doskonałe brzmienie',
    rehearsals_acoustic_title: 'Wyciszenie Akustyczne',
    rehearsals_acoustic_desc: 'Salka została przygotowana akustycznie, aby zapewnić czyste i zrównoważone brzmienie. Ogranicza niepożądane odbicia dźwięku, poprawia komfort odsłuchu i pozwala skupić się na muzyce. Zarezerwuj termin i usłysz różnicę już od pierwszej próby',
    rehearsals_booking_title: 'Elastyczna Rezerwacja',
    rehearsals_booking_desc: 'Mamy wolne terminy na wynajem godzinowy aż i stale terminy. W razie jakichkolwiek pytań napisz do nas lub właśnie zarezerwuj nawet przez stronę internetową',
    rehearsals_climate_title: 'Komfort i wsparcie',
    rehearsals_climate_desc: 'Na miejscu gratis masz kawę lub herbatę. Wsparcie przez cały czas prób lub nagrań. WC i klima. Jeśli czegoś potrzebujesz po prostu zapytaj o tym administratora',
    rent_title: 'Wynajem Sprzętu',
    rent_desc: 'Wynajmij profesjonalny sprzęt muzyczny i nagłośnieniowy na Twoje wydarzenie.',
    rent_pa_title: 'Systemy Nagłośnieniowe',
    rent_pa_desc: 'Estradowe systemy nagłośnienia max 800 Watt do dyspozycji',
    rent_mics_title: 'Mikrofony',
    rent_mics_desc: 'Mikrofony do każdego zastosowania marek Shure, AKG, Audix, Sennheiser, Behringer',
    rent_stage_title: 'Sprzęt Sceniczny',
    rent_stage_desc: 'Kable, statywy, klawisze i akcesoria sceniczne',
    rent_recording_title: 'Wzmacniacze i kolumny',
    rent_recording_desc: 'Wzmacniacze gitarowe lampowe Marshall, Randall, Peavey, Blackstar i basowe Darkglass i Warwick',
    price_title: 'Cennik',
    price_subtitle: 'Przejrzyste ceny za profesjonalne usługi',
    price_recording_name: 'Nagrywanie',
    price_recording_feature1: 'Wsparcie inżyniera dźwięku',
    price_recording_feature2: 'Pełny dostęp do sprzętu',
    price_recording_feature3: 'Dostarczenie plików cyfrowych',
    price_recording_feature4: 'Jedna korekta w cenie',
    price_rehearsal_name: 'Próby',
    price_rehearsal_feature1: 'Pełen backline na miejscu',
    price_rehearsal_feature2: 'System nagłośnienia',
    price_rehearsal_feature3: 'Elastyczne terminy',
    price_rehearsal_feature4: 'Gratis kable do próby',
    price_rental_name: 'Wynajem Sprzętu',
    price_rental_feature1: 'System nagłośnienia',
    price_rental_feature2: 'Mikrofony, syntezator, kable i akcesoria',
    price_rental_feature3: 'Perkusja',
    price_rental_feature4: 'Wzmacniacze i kolumny gitarowe i basowe',
    price_rental_feature5: 'Wsparcie techniczne',
    price_rental_feature6: 'Możliwa dostawa',
    price_mixing_name: 'Mixing & Mastering',
    price_mixing_feature1: 'Edycja i mastering w cenie',
    price_mixing_feature2: 'Nieograniczone korekty',
    price_mixing_feature3: 'Jakość na poziomie branżowym',
    price_mixing_feature4: 'Pomoc w publikacji',
    price_from: 'od',
    price_optional: 'Do ustalenia',
    footer_tagline: 'Profesjonalne Studio Nagraniowe i Sale Prób',
    contact_title: 'Kontakt',
    contact_subtitle: 'Napisz do nas i zarezerwuj swój termin',
    contact_name: 'Imię',
    contact_email: 'Email',
    contact_message: 'Wiadomość',
    contact_send: 'Wyślij',
    contact_success_title: 'Wiadomość wysłana',
    contact_success_desc: 'Dziękujemy! Odpowiemy najszybciej jak to możliwe.',
    contact_error_title: 'Błąd wysyłania',
    contact_error_desc: 'Spróbuj ponownie lub napisz bezpośrednio na support@sanctum-sa.com',
    contact_address: 'Adres',
    contact_phone: 'Telefon',
    contact_button: 'Skontaktuj się z nami',
    studio_gear_title: 'Sprzęt Studia',
    studio_gear_button: 'Zobacz pełną listę sprzętu',
    studio_gear_watch: 'Zobacz',
    book_button: 'Zarezerwuj',
  },
  en: {
    nav_recording: 'Recording',
    nav_rehearsals: 'Rehearsals',
    nav_rent: 'Rent',
    nav_price: 'Price',
    nav_contact: 'Contact',
    hero_title: 'Professional Recording Studio',
    hero_subtitle: 'Highest quality recordings in the heart of the city',
    stat_clients: 'clients',
    stat_songs: 'released songs',
    stat_rehearsals: 'rehearsals',
    stat_rating: '5 star clients rating',
    recording_title: 'Recording Services',
    recording_desc: 'We offer comprehensive recording services using state-of-the-art equipment and an experienced team of sound engineers.',
    recording_vocal_title: 'Vocal Recording',
    recording_vocal_desc: 'Vocal recording in a studio equipped with modern gear. We record for music tracks, rap, podcasts, commercials, and more. With us, you can expect clear sound, a comfortable atmosphere, and an individual approach that lets you fully unlock the potential of your voice',
    recording_instrument_title: 'Instrument Recording',
    recording_instrument_desc: 'Professional recordings of musical instruments in perfectly prepared acoustic conditions. We record guitars, bass, drums, keyboard, string, and wind instruments, ensuring the highest sound quality. We have top-tier equipment and microphones from brands such as Audix, Shure, Behringer, AKG, and Sennheiser, guaranteeing natural, detailed sound ready for mixing and mastering',
    recording_mixing_title: 'Mixing & Mastering',
    recording_mixing_desc: 'Professional mixing and mastering. We ensure the right balance, dynamics, and space in the recording so your music sounds great on all platforms and playback systems. Every project is treated individually, highlighting its character and potential. We also offer vocal editing, drum alignment, and more',
    recording_production_title: 'Audio Production',
    recording_production_desc: 'Have a song idea but do not know how to turn it into a professional track? We offer comprehensive music production from the first concept to the final material ready for release. We help develop arrangements, record vocals and instruments, and then handle editing, mixing, and mastering',
    rehearsals_title: 'Rehearsal Rooms',
    rehearsals_desc: 'Professional rehearsal rooms equipped with full backline and sound system. Perfect for bands of any genre.',
    rehearsals_backline_title: 'Full Backline',
    rehearsals_backline_desc: 'We offer tube guitar and bass amplifiers, a fully equipped drum kit for playing, and high-quality 800 Watt PA equipment. Everything is regularly serviced, ensuring reliability, playing comfort and excellent sound',
    rehearsals_acoustic_title: 'Acoustic Treatment',
    rehearsals_acoustic_desc: 'The room is acoustically prepared to provide clean and balanced sound. It reduces unwanted reflections, improves listening comfort and allows you to focus on the music. Book your session and hear the difference from the very first rehearsal',
    rehearsals_booking_title: 'Flexible Booking',
    rehearsals_booking_desc: 'We have available slots for hourly rental and regular long-term sessions. If you have any questions, write to us or book directly through the website',
    rehearsals_climate_title: 'Comfort and support',
    rehearsals_climate_desc: 'Free coffee or tea on site. Support throughout rehearsals or recordings. Toilet and air conditioning. If you need anything, just ask the administrator',
    rent_title: 'Equipment Rental',
    rent_desc: 'Rent professional music and sound equipment for your event.',
    rent_pa_title: 'PA Systems',
    rent_pa_desc: 'Stage PA systems up to 800 Watt available',
    rent_mics_title: 'Microphones',
    rent_mics_desc: 'Microphones for every application from Shure, AKG, Audix, Sennheiser, Behringer',
    rent_stage_title: 'Stage Equipment',
    rent_stage_desc: 'Cables, stands, keyboards and stage accessories',
    rent_recording_title: 'Amplifiers and Cabinets',
    rent_recording_desc: 'Tube guitar amplifiers Marshall, Randall, Peavey, Blackstar and bass amplifiers Darkglass and Warwick',
    price_title: 'Pricing',
    price_subtitle: 'Transparent pricing for professional services',
    price_recording_name: 'Recording',
    price_recording_feature1: 'Sound engineer support',
    price_recording_feature2: 'Full equipment access',
    price_recording_feature3: 'Digital file delivery',
    price_recording_feature4: 'One revision included',
    price_rehearsal_name: 'Rehearsal',
    price_rehearsal_feature1: 'Full backline on-site',
    price_rehearsal_feature2: 'PA system',
    price_rehearsal_feature3: 'Flexible dates',
    price_rehearsal_feature4: 'Free cables for rehearsal',
    price_rental_name: 'Equipment Rental',
    price_rental_feature1: 'Professional PA system',
    price_rental_feature2: 'Microphones, synths, cables and accessories',
    price_rental_feature3: 'Drums',
    price_rental_feature4: 'Guitar and bass amps and cabinets',
    price_rental_feature5: 'Technical support',
    price_rental_feature6: 'Delivery available',
    price_mixing_name: 'Mixing & Mastering',
    price_mixing_feature1: 'Editing and mastering included',
    price_mixing_feature2: 'Unlimited revisions',
    price_mixing_feature3: 'Industry standard quality',
    price_mixing_feature4: 'Publishing assistance',
    price_from: 'from',
    price_optional: 'Optional',
    footer_tagline: 'Professional Recording Studio & Rehearsal Space',
    contact_title: 'Contact',
    contact_subtitle: 'Feel free to reach out and book your appointment',
    contact_name: 'Name',
    contact_email: 'Email',
    contact_message: 'Message',
    contact_send: 'Send',
    contact_success_title: 'Message sent',
    contact_success_desc: 'Thanks! We will get back to you as soon as possible.',
    contact_error_title: 'Sending failed',
    contact_error_desc: 'Please try again or email us directly at support@sanctum-sa.com',
    contact_address: 'Address',
    contact_phone: 'Phone',
    contact_button: 'Contact Us',
    studio_gear_title: 'Studio Gear',
    studio_gear_button: 'View full equipment list',
    studio_gear_watch: 'Watch',
    book_button: 'Book',
  },
  uk: {
    nav_recording: 'Запис',
    nav_rehearsals: 'Репетиції',
    nav_rent: 'Оренда',
    nav_price: 'Ціни',
    nav_contact: 'Контакт',
    hero_title: 'Професійна Студія Звукозапису',
    hero_subtitle: 'Найвища якість записів у центрі міста',
    stat_clients: 'клієнтів',
    stat_songs: 'випущених пісень',
    stat_rehearsals: 'репетицій',
    stat_rating: '5★ рейтинг клієнтів',
    recording_title: 'Послуги Звукозапису',
    recording_desc: 'Ми пропонуємо комплексні послуги звукозапису з використанням найсучаснішого обладнання та досвідченої команди звукоінженерів.',
    recording_vocal_title: 'Запис Вокалу',
    recording_vocal_desc: 'Запис вокалу в студії, обладнаній сучасним обладнанням. Записуємо для музичних творів, репу, подкастів, реклами та інших завдань. У нас ви можете розраховувати на чисте звучання, комфортну атмосферу та індивідуальний підхід, які дозволять повноцінно розкрити потенціал вашого голосу',
    recording_instrument_title: 'Запис Інструментів',
    recording_instrument_desc: 'Професійний запис музичних інструментів у досконало підготовлених акустичних умовах. Реєструємо гітари, бас, ударні, клавішні, струнні та духові інструменти, піклуючись про найвищу якість звуку. У нас обладнання найвищого рівня, мікрофони таких брендів як Audix, Shure, Behringer, AKG, Sennheiser гарантують природне, детальне звучання, готове до мікшування та мастерингу',
    recording_mixing_title: 'Мікшування та Мастеринг',
    recording_mixing_desc: 'Професійний мікс та мастеринг. Ми дбаємо про правильний баланс, динаміку та простір у записі, щоб ваша музика звучала чудово на всіх платформах та системах відтворення. Кожен проєкт ми розглядаємо індивідуально, підкреслюючи його характер і потенціал. Ми також пропонуємо редагування вокалу, вирівнювання ударних треків та інше',
    recording_production_title: 'Аудіо Продакшн',
    recording_production_desc: 'Маєте ідею пісні, але не знаєте, як перетворити її на професійний твір? Ми пропонуємо комплексну музичну реалізацію від першої концепції до готового матеріалу для публікації. Допомагаємо у розробці аранжувань, реалізуємо запис вокалу та інструментів, а потім займаємося редагуванням, мікшуванням та мастерингом',
    rehearsals_title: 'Репетиційні Зали',
    rehearsals_desc: 'Професійні репетиційні зали, обладнані повним беклайном та звуковою системою. Ідеально підходять для гуртів будь-якого жанру.',
    rehearsals_backline_title: 'Повний Беклайн',
    rehearsals_backline_desc: 'Ми пропонуємо лампові гітарні та басові підсилювачі, повністю укомплектовану ударну установку для гри, та високоякісне звукове обладнання 800 Ват. Усе регулярно обслуговується, обладнання забезпечує надійність, комфорт гри та чудовий звук',
    rehearsals_acoustic_title: 'Акустична Обробка',
    rehearsals_acoustic_desc: 'Зал акустично підготовлений, щоб забезпечити чистий та збалансований звук. Він зменшує небажані відбиття звуку, покращує комфорт прослуховування і дозволяє зосередитися на музиці. Забронюйте сеанс і почуйте різницю вже з першої репетиції',
    rehearsals_booking_title: 'Гнучке Бронювання',
    rehearsals_booking_desc: 'У нас є вільні слоти для погодинної оренди та регулярних довгострокових занять. У разі будь-яких запитань напишіть нам або забронюйте прямо через веб-сайт',
    rehearsals_climate_title: 'Комфорт і підтримка',
    rehearsals_climate_desc: 'Безкоштовна кава або чай на місці. Підтримка протягом усіх репетицій або записів. Туалет та кондиціонер. Якщо вам щось потрібно, просто запитайте адміністратора',
    rent_title: 'Оренда Обладнання',
    rent_desc: 'Орендуйте професійне музичне та звукове обладнання для вашої події.',
    rent_pa_title: 'Звукові Системи',
    rent_pa_desc: 'Сценічні звукові системи до 800 Ват у вашому розпорядженні',
    rent_mics_title: 'Мікрофони',
    rent_mics_desc: 'Мікрофони для будь-якого застосування брендів Shure, AKG, Audix, Sennheiser, Behringer',
    rent_stage_title: 'Сценічне Обладнання',
    rent_stage_desc: 'Кабелі, стійки, клавіші та сценічні аксесуари',
    rent_recording_title: 'Підсилювачі та кабінети',
    rent_recording_desc: 'Лампові гітарні підсилювачі Marshall, Randall, Peavey, Blackstar та басові підсилювачі Darkglass і Warwick',
    price_title: 'Ціни',
    price_subtitle: 'Прозоре ціноутворення на професійні послуги',
    price_recording_name: 'Запис',
    price_recording_feature1: 'Підтримка звукоінженера',
    price_recording_feature2: 'Повний доступ до обладнання',
    price_recording_feature3: 'Доставка цифрових файлів',
    price_recording_feature4: 'Одна правка включена',
    price_rehearsal_name: 'Репетиція',
    price_rehearsal_feature1: 'Повний беклайн на місці',
    price_rehearsal_feature2: 'Звукова система',
    price_rehearsal_feature3: 'Гнучкі дати',
    price_rehearsal_feature4: 'Безкоштовні кабелі для репетиції',
    price_rental_name: 'Оренда Обладнання',
    price_rental_feature1: 'Професійна звукова система',
    price_rental_feature2: 'Преміальні мікрофони',
    price_rental_feature3: 'Ударна установка',
    price_rental_feature4: 'Гітарні та басові підсилювачі і кабінети',
    price_rental_feature5: 'Технічна підтримка',
    price_rental_feature6: 'Можлива доставка',
    price_mixing_name: 'Мікшування та Мастеринг',
    price_mixing_feature1: 'Редагування та мастеринг включено',
    price_mixing_feature2: 'Необмежені правки',
    price_mixing_feature3: 'Якість промислового стандарту',
    price_mixing_feature4: 'Допомога в публікації',
    price_from: 'від',
    price_optional: 'Опціонально',
    footer_tagline: 'Професійна Студія Звукозапису та Репетиційні Зали',
    contact_title: 'Контакт',
    contact_subtitle: "Зв'яжіться з нами та забронюйте свій візит",
    contact_name: "Ім'я",
    contact_email: 'Email',
    contact_message: 'Повідомлення',
    contact_send: 'Надіслати',
    contact_success_title: 'Повідомлення надіслано',
    contact_success_desc: 'Дякуємо! Ми відповімо якнайшвидше.',
    contact_error_title: 'Помилка надсилання',
    contact_error_desc: 'Спробуйте ще раз або напишіть на support@sanctum-sa.com',
    contact_address: 'Адреса',
    contact_phone: 'Телефон',
    contact_button: 'Зв\'яжіться з нами',
    studio_gear_title: 'Обладнання Студії',
    studio_gear_button: 'Переглянути повний список обладнання',
    studio_gear_watch: 'Переглянути',
    book_button: 'Забронювати',
  },
  be: {
    nav_recording: 'Запіс',
    nav_rehearsals: 'Рэпетыцыі',
    nav_rent: 'Арэнда',
    nav_price: 'Кошты',
    nav_contact: 'Кантакт',
    hero_title: 'Прафесійная Студыя Гукозапісу',
    hero_subtitle: 'Найвышэйшая якасць запісаў у цэнтры горада',
    stat_clients: 'кліентаў',
    stat_songs: 'выпушчаных песень',
    stat_rehearsals: 'рэпетыцый',
    stat_rating: '5★ рэйтынг кліентаў',
    recording_title: 'Паслугі Гукозапісу',
    recording_desc: 'Мы прапануем комплексныя паслугі гукозапісу з выкарыстаннем найсучаснейшага абсталявання і вопытнай каманды гукарэжысёраў.',
    recording_vocal_title: 'Запіс Вакалу',
    recording_vocal_desc: 'Запіс вакалу ў студыі, абсталяванай сучасным абсталяваннем. Запісваем для музычных твораў, рэпу, падкастаў, рэкламы і іншага. У нас вы можаце чакаць чысты гук, камфортную атмасферу і індывідуальны падыход, якія дазволяць поўнасцю раскрыць патэнцыял вашага голасу',
    recording_instrument_title: 'Запіс Інструментаў',
    recording_instrument_desc: 'Прафесійны запіс музычных інструментаў у даканала падрыхтаваных акустычных умовах. Рэгіструем гітары, бас, ударныя, клавішныя, струнныя і духовыя інструменты, клапоцячыся пра найвышэйшую якасць гуку. У нас абсталяванне высокага класа, мікрафоны такіх брэндаў як Audix, Shure, Behringer, AKG, Sennheiser гарантуюць натуральнае, дэтальнае гучанне, гатовае да мікшавання і мастэрынгу',
    recording_mixing_title: 'Мікшаванне і Мастэрынг',
    recording_mixing_desc: 'Прафесійны мікс і мастэрынг. Мы дбаем пра адпаведны баланс, дынаміку і прастору ў запісе, каб ваша музыка гучала выдатна на ўсіх платформах і сістэмах праслухоўвання. Кожны праект мы трактуем індывідуальна, падкрэсліваючы яго характар і патэнцыял. Мы таксама прапануем рэдагаванне вакалу, выпраўленне ўдарных трэкаў і іншае',
    recording_production_title: 'Аўдыё Прадакшн',
    recording_production_desc: 'У вас ёсць ідэя песні, але вы не ведаеце, як ператварыць яе ў прафесійны твор? Мы прапануем комплексную музычную рэалізацыю ад першай канцэпцыі да гатовага матэрыялу для публікацыі. Дапамагаем у распрацоўцы аранжыровак, рэалізуем запіс вакалу і інструментаў, а затым займаемся рэдагаваннем, мікшаваннем і мастэрынгам',
    rehearsals_title: 'Рэпетыцыйныя Залы',
    rehearsals_desc: 'Прафесійныя рэпетыцыйныя залы, абсталяваныя поўным беклайнам і гукавой сістэмай. Ідэальна падыходзяць для гуртоў любога жанру.',
    rehearsals_backline_title: 'Поўны Беклайн',
    rehearsals_backline_desc: 'Мы прапануем лампавыя гітарныя і басавыя ўзмацняльнікі, поўнасцю ўкамплектаваную ударную ўстаноўку для гульні, і высакаякаснае гукавое абсталяванне 800 Ват. Усё рэгулярна абслугоўваецца, абсталяванне забяспечвае надзейнасць, камфорт гульні і выдатны гук',
    rehearsals_acoustic_title: 'Акустычная Апрацоўка',
    rehearsals_acoustic_desc: 'Зала акустычна падрыхтаваная, каб забяспечыць чысты і збалансаваны гук. Яна памяншае непажаданыя адбіванні гуку, паляпшае камфорт праслухоўвання і дазваляе зоследзіцца на музыцы. Забраніруйце сеанс і пачуйце розніцу ўжо з першай рэпетыцыі',
    rehearsals_booking_title: 'Гібкае Браніраванне',
    rehearsals_booking_desc: 'У нас ёсць вольныя слаты для пагадзіннай арэнды і рэгулярных доўгатэрміновых заняткаў. У выпадку любых пытанняў напішыце нам або забраніруйце прама праз вэб-сайт',
    rehearsals_climate_title: 'Камфорт і падтрымка',
    rehearsals_climate_desc: 'Бясплатная кава ці гарбатка на месцы. Падтрымка на працягу ўсіх рэпетыцый або запісаў. Туалет і кандыцыянер. Калі вам нешта патрэбна, проста спытайце адміністратара',
    rent_title: 'Арэнда Абсталявання',
    rent_desc: 'Арандуйце прафесійнае музычнае і гукавое абсталяванне для вашай падзеі.',
    rent_pa_title: 'Гукавыя Сістэмы',
    rent_pa_desc: 'Сцэнічныя гукавыя сістэмы да 800 Ват у вашым распараджэнні',
    rent_mics_title: 'Мікрафоны',
    rent_mics_desc: 'Мікрафоны для любога прымянення брэндаў Shure, AKG, Audix, Sennheiser, Behringer',
    rent_stage_title: 'Сцэнічнае Абсталяванне',
    rent_stage_desc: 'Кабелі, стойкі, клавішы і сцэнічныя аксесуары',
    rent_recording_title: 'Прадваральнікі і калонкі',
    rent_recording_desc: 'Лампавыя гітарныя прадваральнікі Marshall, Randall, Peavey, Blackstar і басавыя прадваральнікі Darkglass і Warwick',
    price_title: 'Кошты',
    price_subtitle: 'Празрыстае цэнаўтварэнне на прафесійныя паслугі',
    price_recording_name: 'Запіс',
    price_recording_feature1: 'Падтрымка гукарэжысёра',
    price_recording_feature2: 'Поўны доступ да абсталявання',
    price_recording_feature3: 'Дастаўка лічбавых файлаў',
    price_recording_feature4: 'Адна праўка ўключана',
    price_rehearsal_name: 'Рэпетыцыя',
    price_rehearsal_feature1: 'Поўны беклайн на месцы',
    price_rehearsal_feature2: 'Гукавая сістэма',
    price_rehearsal_feature3: 'Гібкія даты',
    price_rehearsal_feature4: 'Бясплатныя кабелі для рэпетыцыі',
    price_rental_name: 'Арэнда Абсталявання',
    price_rental_feature1: 'Прафесійная гукавая сістэма',
    price_rental_feature2: 'Прэміяльныя мікрафоны',
    price_rental_feature3: 'Барабаны',
    price_rental_feature4: 'Гітарныя і басавыя прадваральнікі і калонкі',
    price_rental_feature5: 'Тэхнічная падтрымка',
    price_rental_feature6: 'Магчымая дастаўка',
    price_mixing_name: 'Мікшаванне і Мастэрынг',
    price_mixing_feature1: 'Рэдагаванне і мастэрынг уключаны',
    price_mixing_feature2: 'Неабмежаваныя праўкі',
    price_mixing_feature3: 'Якасць прамысловага стандарту',
    price_mixing_feature4: 'Дапамога ў публікацыі',
    price_from: 'ад',
    price_optional: 'Апцыянальна',
    footer_tagline: 'Прафесійная Студыя Гукозапісу і Рэпетыцыйныя Залы',
    contact_title: 'Кантакт',
    contact_subtitle: 'Звяжыцеся з намі і забраніруйце свой візіт',
    contact_name: 'Імя',
    contact_email: 'Email',
    contact_message: 'Паведамленне',
    contact_send: 'Адправіць',
    contact_success_title: 'Паведамленне адпраўлена',
    contact_success_desc: 'Дзякуем! Мы адкажам як мага хутчэй.',
    contact_error_title: 'Памылка адпраўкі',
    contact_error_desc: 'Паспрабуйце яшчэ раз або напішыце на support@sanctum-sa.com',
    contact_address: 'Адрас',
    contact_phone: 'Тэлефон',
    contact_button: 'Звяжыцеся з намі',
    studio_gear_title: 'Абсталяванне Студыі',
    studio_gear_button: 'Паглядзець поўны спіс абсталявання',
    studio_gear_watch: 'Паглядзець',
    book_button: 'Забраніраваць',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Detect browser language and set default
const detectBrowserLanguage = (): Language => {
  const browserLang = navigator.language.toLowerCase();
  
  // Map browser language codes to our supported languages
  if (browserLang.startsWith('pl')) return 'pl';
  if (browserLang.startsWith('uk')) return 'uk';
  if (browserLang.startsWith('be')) return 'be';
  if (browserLang.startsWith('en')) return 'en';
  
  // Default to English if language not supported
  return 'en';
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check if language is stored in localStorage
    const storedLang = localStorage.getItem('language') as Language | null;
    if (storedLang && ['pl', 'en', 'uk', 'be'].includes(storedLang)) {
      return storedLang;
    }
    // Otherwise, detect browser language
    return detectBrowserLanguage();
  });

  // Save language preference to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
